### PR TITLE
Generator of ActionBars' properties

### PR DESCRIPTION
**Pull request by lucky-dev**
#### for original API

- var android.app.ActionBar.customView: android.view.View?
- var android.app.ActionBar.displayOptions: Int
- val android.app.ActionBar.height: Int
- val android.app.ActionBar.navigationItemCount: Int
- var android.app.ActionBar.navigationMode: Int
- val android.app.ActionBar.selectedNavigationIndex: Int
- var android.app.ActionBar.subtitle: CharSequence?
- var android.app.ActionBar.subtitleResource: Int
- val android.app.ActionBar.tabCount: Int
- var android.app.ActionBar.title: CharSequence?
- var android.app.ActionBar.titleResource: Int
- var android.app.ActionBar.icon
- var android.app.ActionBar.logo
- var android.app.ActionBar.selectedNavigationItem
- var android.app.ActionBar.displayUseLogoEnabled
- var android.app.ActionBar.displayShowHomeEnabled
- var android.app.ActionBar.displayHomeAsUpEnabled
- var android.app.ActionBar.displayShowTitleEnabled
- var android.app.ActionBar.displayShowCustomEnabled
- var android.app.ActionBar.backgroundDrawable
- var android.app.ActionBar.stackedBackgroundDrawable
- var android.app.ActionBar.splitBackgroundDrawable
- var android.app.ActionBar.homeButtonEnabled
- var android.app.ActionBar.homeAsUpIndicator
- val android.app.Activity.actionBar: android.app.ActionBar?
- val android.app.Activity.fragmentManager: android.app.FragmentManager
- val android.app.Activity.menuInflater: android.view.MenuInflater

#### for support-library API

- var android.support.v7.app.ActionBar.customView: android.view.View?
- var android.support.v7.app.ActionBar.displayOptions: Int
- val android.support.v7.app.ActionBar.height: Int
- val android.support.v7.app.ActionBar.navigationItemCount: Int
- var android.support.v7.app.ActionBar.navigationMode: Int
- val android.support.v7.app.ActionBar.selectedNavigationIndex: Int
- val android.support.v7.app.ActionBar.selectedTab: android.support.v7.app.ActionBar.Tab?
- var android.support.v7.app.ActionBar.subtitle: CharSequence?
- var android.support.v7.app.ActionBar.subtitleResource: Int
- val android.support.v7.app.ActionBar.tabCount: Int
- var android.support.v7.app.ActionBar.title: CharSequence?
- var android.support.v7.app.ActionBar.titleResource: Int
- var android.support.v7.app.ActionBar.displayHomeAsUpEnabled
- var android.support.v7.app.ActionBar.selectedNavigationItem
- var android.support.v7.app.ActionBar.displayUseLogoEnabled
- var android.support.v7.app.ActionBar.logo
- var android.support.v7.app.ActionBar.displayShowTitleEnabled
- var android.support.v7.app.ActionBar.displayShowHomeEnabled
- var android.support.v7.app.ActionBar.icon
- var android.support.v7.app.ActionBar.displayShowCustomEnabled
- var android.support.v7.app.ActionBar.backgroundDrawable
- var android.support.v7.app.ActionBar.stackedBackgroundDrawable
- var android.support.v7.app.ActionBar.splitBackgroundDrawable
- var android.support.v7.app.ActionBar.homeButtonEnabled
- var android.support.v7.app.ActionBar.homeAsUpIndicator
- val android.support.v4.app.FragmentActivity.supportFragmentManager: android.support.v4.app.FragmentManager?
- val android.support.v7.app.AppCompatActivity.menuInflater: android.view.MenuInflater?
- val android.support.v7.app.AppCompatActivity.supportActionBar: android.support.v7.app.ActionBar?

_P.S. These methods are most popular, in my opinion._

#### Searching fragments:
```
fragmentManager.find<MyFragment>(MyFragment.TAG) // By tag
fragmentManager.find<MyFragment>(R.id.my_fragment) // By id
```
#### Fragments' transactions:
```
fragmentManager.transactions {
  add(MyFragment(), MyFragment.TAG)
}.commit()
```

### CODE REVIEW

**Comment by yanex** [comment]
This approach is not so good as it is not extensible (`ActionBar` class names are hardcoded, and it would take the same time to support any other class in Android SDK).
Anko now can resolve external annotations, so putting a custom annotation on `ActionBar` class would be much cleaner solution.

**Comment by lucky-dev** [comment]
`it would take the same time to support any other class in Android SDK`

I agree with you. I have two questions:

1. Could you give an example of this: `putting a custom annotation on ActionBar class would be much cleaner solution`. It's interesting.
2. Will you use "external annotations" for other classes of Android SDK?

**Comment by yanex** [comment]
It's actually very easy. I added a custom annotation in https://github.com/JetBrains/anko/commit/ed39f2cf6a7464b444e2f9f91e6066a42c840a27 to support  `_Layout` helper class generation for `ImageSwitcher`.

**Comment by lucky-dev** [comment]
Thanks for explanation

**Pull request closed without merging**
