### PR TITLE
Update gradle version

### PR DESCRIPTION
**Pull request by cypressious**

### CODE REVIEW

**Comment by Ribesg** [comment]
Any reason to use an non-stable version?

**Comment by cypressious** [comment]
2.8 is supposedly faster than 2.7 and didn't cause any issues in my personal projects so far. We could change it to 2.7 stable, too. That's still better than 2.2.

**Comment by Ribesg** [comment]
You can now update this to 2.8, I guess.

**Comment by cypressious** [comment]
done

**Comment by yanex** [comment]
Merged manually: https://github.com/JetBrains/anko/commit/2a67399a9289aa77ecf1df45341061c80fd1c7da. Thanks!

**Pull request closed without merging**
